name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Client Api
      run: cargo build --verbose --manifest-path ./game_client_api/Cargo.toml
    - name: Run tests Client Api
      run: cargo test --verbose --manifest-path ./game_client_api/Cargo.toml
    - name: Build Core
      run: cargo build --verbose --manifest-path ./core/Cargo.toml
    - name: Run tests Core
      run: cargo test --verbose --manifest-path ./core/Cargo.toml
    - name: Build Server
      run: cargo build --verbose --manifest-path ./server/Cargo.toml
    - name: Run tests Server
      run: cargo test --verbose --manifest-path ./server/Cargo.toml
